twig_component:
    anonymous_template_directory: '_components/'
    defaults:
        # Namespace & directory for components
        App\Loan\UI\Twig\Component\:
            template_directory: '_components/loan/'
            name_prefix: Loan
